name: Ghost Development server

on:
  push:
    branches:
    - main

jobs:
  build:
    # using Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v0.1.4
      #this installs node and npm for us
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      # this allows for re-using node_modules caching, making builds a bit faster.
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm cache clean --force
      - run: npm install
      - run: npm install -g @angular/cli > /dev/null
      - run: ng build

      - name: copy file via ssh key
        uses: appleboy/scp-action@0.1.4
        with:
          port: 22
          host:  ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          username:  ${{ secrets.USERNAME }}
          source: "./dist/api-panel"
          target: "/var/www/html"
          strip_components: 2
